rul/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('random', views.random_selector, name='random'),
    path('rainbow', views.rainbow, name='rainbow'),
    path('insta_glam_selector', views.insta_glam_selector, name='insta_glam'),
    path('user_shade', views.user_shade, name='user_shade'),
    path('palette_request', views.palette_request, name='palette_request'),
    path('thanks',  TemplateView.as_view(template_name="rul/thanks.html"), name='thanks'),

]

rulette/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
                  path('', include('rul.urls')),
                  path('admin/', admin.site.urls),
                  path('accounts/', include('django_registration.backends.one_step.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

rul/models.py
import easy_thumbnails
from django.db import models
from django_registration.forms import User
from image_cropping import ImageRatioField
from image_cropping.utils import get_backend

from .storage import CustomStorage


class Seller(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Palette(models.Model):
    name = models.CharField(max_length=200)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    photo = models.ImageField(blank=True, upload_to='palettes')
    published = models.BooleanField(default=False)

    # seller = models.DateTimeField('date published')
    def __str__(self):
        return f'{self.name} by {self.seller}.'


custom_store = CustomStorage()


class Shade(models.Model):
    COLORS = [('P', 'Pink'),
              ('L', 'Lilac'),
              ('C', 'Corall'),
              ('R', 'Red'),
              ('O', 'Orange'),
              ('Y', 'Yellow'),
              ('G', 'Green'),
              ('B', 'Blue'),
              ('Pu', 'Purple'),
              ('Bk', 'Black'),
              ('Br', 'Brown'),
              ('Be', 'Beige'),
              ('Gr', 'Gray'),
              ('W', 'White'),
              ('S', 'Silver'),
              ('Co', 'Cooper'),
              ('Go', 'Gold'), ]
    TEXTURES = [('M', 'Matte'),
                ('Sh', 'Shimmer'),
                ('Sp', 'Sparkle'),
                ('G', 'Glitter'),
                ('T', 'Topper'),
                ('F', 'Foil'),
                ]
    DARKNES = [('1', 'Blackl'),
               ('2', 'dark'),
               ('3', 'medium'),
               ('4', 'light'),
               ('5', 'white'),
               ]
    palette = models.ForeignKey(Palette, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    number = models.IntegerField()
    color = models.CharField(max_length=200, choices=COLORS)
    second_color = models.CharField(blank=True, max_length=200, choices=COLORS)
    darkness = models.CharField(max_length=200, choices=DARKNES)
    texture = models.CharField(max_length=200, choices=TEXTURES)
    photo = models.ImageField(blank=True, storage=custom_store, upload_to='shades')
    cropping = ImageRatioField('photo', '40x40')

    def __str__(self):
        return f'{self.palette.name} - {self.name}.'

    def crop(self):
        try:
            thumbnail_url = get_backend().get_thumbnail_url(
                self.photo,
                {
                    'size': (430, 360),
                    'box': self.cropping,
                    'crop': True,
                    'detail': True,
                }
            )
        except easy_thumbnails.exceptions.InvalidImageFormatError:
            thumbnail_url = ''
        return thumbnail_url


class UserShade(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shade = models.ForeignKey(Shade, on_delete=models.CASCADE)


class PaletteRequest(models.Model):
    name = models.CharField(max_length=200)
    seller = models.CharField(max_length=200)
    photo_URL = models.CharField(max_length=600, blank=True)
    number_of_colors = models.IntegerField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    processed = models.BooleanField()
    date = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.name} - {self.seller}.'

rul/forms.py
from django import forms

from .models import PaletteRequest


class PaletteRequestForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = PaletteRequest
        exclude = ('user', 'processed', 'date')

rul/views.py
import re

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django_registration.forms import User

from .forms import PaletteRequestForm
from .models import Shade, Palette, UserShade, PaletteRequest


def index(request):
    return render(request, 'rul/index.html', {})


@login_required
def random_selector(request):
    shades_id = user_shades(request.user.pk)
    shades = Shade.objects.filter(id__in=shades_id).select_related('palette__seller').all().order_by('?')[:4]
    if len(shades) >= 4:
        context = {'shades_list': shades}
    else:
        context = {"error": 1}
    return render(request, 'rul/random.html', context)


@login_required
def insta_glam_selector(request):
    shades_id = user_shades(request.user.pk)
    crease = Shade.objects.select_related('palette__seller').filter(
        texture='M', darkness=3, id__in=shades_id).all().order_by('?')[:1]

    inner = Shade.objects.select_related('palette__seller').filter(
        id__in=shades_id).filter(
        Q(texture='Sh') | Q(texture='Sp') | Q(texture='G') | Q(darkness__gt=3)).all().order_by('?')[:1]

    outer_v = Shade.objects.select_related('palette__seller').filter(
        id__in=shades_id, darkness__lt=3).all().order_by('?')[:1]

    blending = Shade.objects.select_related('palette__seller').filter(
        id__in=shades_id, darkness__gt=3).all().order_by('?')[:1]

    try:
        context = {"shades_list": [crease[0], inner[0], outer_v[0], blending[0]]}
    except IndexError:
        context = {"error": 1}
    return render(request, 'rul/insta_glam_selector.html', context)


@login_required
def rainbow(request):
    colors = {}
    shades_id = user_shades(request.user.pk)
    shades = Shade.objects.select_related('palette__seller').filter(id__in=shades_id).all()
    for color in Shade.COLORS:
        colors[color[1]] = [s for s in shades if s.color == color[0]]

    return render(request, 'rul/rainbow.html', {'colors': colors})


@login_required
def user_shade(request):
    user = User.objects.get(id=request.user.pk)
    published_palettes = Palette.objects.filter(published=True).values_list('id', flat=True)
    published_shades = Shade.objects.filter(palette__in=published_palettes).values_list('id', flat=True)
    shades = Shade.objects.select_related('palette__seller').filter(id__in=published_shades).order_by('number').all()
    shades_ids = [s.id for s in shades]
    if request.method == 'POST':
        # in assumption than name of input is id of shade
        UserShade.objects.filter(user_id=user.id).delete()
        for key, value in request.POST.items():
            if value == 'on':
                _, s_id = re.split(r's', key)
                key = int(s_id)
                if key in shades_ids:
                    shade = Shade.objects.get(id=key)
                    pair = UserShade(user=user, shade=shade)
                    pair.save()
        return HttpResponseRedirect('rainbow')
    # if a GET (or any other method) we'll create a blank form
    else:
        u_shades = user_shades(request.user.pk)
        palettes = Palette.objects.select_related('seller').filter(id__in=published_palettes).all()
        return render(request, 'rul/user_shade.html',
                      {
                          'palettes': palettes,
                          'shades': shades,
                          'user_shades': u_shades})


# technical function
def user_shades(user_id):
    published_palettes = Palette.objects.filter(published=True).values_list('id', flat=True)
    published_shades = Shade.objects.filter(palette__in=published_palettes).values_list('id', flat=True)
    user_shades = UserShade.objects.select_related(
        'shade__palette__seller').filter(user_id=user_id, shade_id__in=published_shades).all()
    return [s.shade.id for s in user_shades]


@login_required
def palette_request(request):
    user = User.objects.get(id=request.user.pk)

    if request.method == 'POST':
        form = PaletteRequestForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            print(form.cleaned_data)
            n_colors = form.cleaned_data.get('number_of_colors')
            req = PaletteRequest(name=form.cleaned_data.get('name'),
                                 seller=form.cleaned_data.get('seller'),
                                 photo_URL=form.cleaned_data.get('photo_URL'),
                                 number_of_colors=n_colors if n_colors else 0,
                                 user=request.user,
                                 processed=False)
            req.save()
            return HttpResponseRedirect('thanks')

rul/templates/rul/snippets/request_form.html
<!-- Modal -->
<form action="palette_request" method="post" id="requestform">
{% csrf_token %}
<div class="modal fade" id="request_mdal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">We will add palette as soon as possible.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          {{request.form.as_p}}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</form>

rul/templates/rul/snippets/shade_with_popup.html
{% if shade %}

<!-- Button trigger modal -->
<span  data-toggle="modal" data-target="#shadeModal{{shade.pk}}">
  <img src="{{shade.crop}}" height="40px"
    data-toggle="tooltip"
    data-placement="top"
    title="{{shade.name}} from  {{shade.palette.name}} by {{shade.palette.seller.name}}."/>
</span>

<!-- Modal -->
<span>
    <div class="modal fade" id="shadeModal{{shade.pk}}" tabindex="-1" role="dialog"  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><b>{{shade.name}}</b> from  {{shade.palette.name}} by {{shade.palette.seller.name}}.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="row">
          <div class="col-5"><img src="{{shade.palette.photo.url}}" height="100px" /></div>
          <div class="col"><p>{{shade.get_color_display }}{% if shade.second_color  %}/{{shade.get_second_color_display}}{% endif %}
             - {{shade.get_darkness_display }} {{shade.get_texture_display }}</p></div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</span>
{% else %}
    <p>Shade is not available.</p>
{% endif %}

rul/templates/rul/snippets/shades_list.html
    <div class="row">
    <div class="col-sm">
        <ul class="p-6">
        {% for shade in shades_list %}
            <li>
                {% include 'rul/snippets/shade_with_popup.html' with shade=shade%}
                {% cycle 'Inner corner' 'Crease' 'Outer V' 'Blending' as part %}
            </li>
        {% endfor %}
        </ul>
    </div>
    <div class="col">
        {% include 'rul/snippets/eye_preview_4.html' with shades_list=shades_list%}
    </div>
   </div>